-- Database initialization script for delivery application
-- NOTE: Schema and indexes are now managed by Liquibase (see src/main/resources/db/changelog/)
-- This file is intentionally empty to allow Liquibase to manage the database schema.
